## Reinforcement Learning

<img align="left" src="image1.png"     style=" width:1000px; padding: 10px; " >

- Reinforcement learning is a subfield of machine learning that focuses on developing algorithms that enable an agent to learn how to make decisions by interacting with an environment. The agent receives feedback in the form of rewards or penalties, and its goal is to learn how to take actions that maximize its cumulative rewards over time.


- In reinforcement learning, the agent interacts with the environment in discrete time steps. At each time step, the agent observes the current state of the environment and selects an action to take based on a policy, which is a function that maps states to actions. The environment then transitions to a new state and provides the agent with a reward signal, which is a scalar value that indicates how well the agent is doing at the current time step. The agent then updates its policy based on the observed state, action, and reward, and continues to interact with the environment.


- The goal of the agent is to learn a policy that maximizes its expected cumulative reward over time. This requires balancing the desire to maximize immediate rewards with the need to explore new actions that may lead to higher long-term rewards. Reinforcement learning algorithms use various techniques to balance exploration and exploitation and learn an optimal policy, such as Q-learning, policy gradient methods, and actor-critic methods.


- Reinforcement learning has many practical applications, including robotics, game playing, recommendation systems, and autonomous vehicles.

- Agent: Learns from trial & error
- Environment: Where the agents moves
- Action: All possible steps agent can take
- State: Current condition in the environment
- Reward: An apraisal of the last action
- Policy: Agent uses to determine the next action based on the current state
- Value: Expected long term return, as opposed to short term reward
- Action-value: Similar to value, but it takes an extra parameter, the current action

## Markov's Decision Process

<img align="left" src="image2.png"     style=" width:400px; padding: 10px; " >

- The mathematical approach for mapping a solution in reinforcement learning is called MDP
- Following parameters are used in attaining a solution in MDP:
    - Set of actions, A
    - Set of states, S
    - Reward, R
    - Policy, pi
    - Value, V
 
- Goal: Find the shortest path between A & D with minimum possible cost
    - Set of states are denoted by nodes
    - Action are denoted by edges
    - Reward is the cost of an edge
    - Policy is the path take to reach the destination

## Q-Learning
- Q(state, action) = R(state, action) + Gamma * Max[Q(next state, all actions]
- The Gamma parameter has a range of 0 to 1 (0 <= Gamma < 1)
  - if Gamma is set closer to zero, agent will tend to consider only immediate rewards - exploitation
  - if Gamma is set closer to one, agent will consider higher rewards - exploration
  
<img align="left" src="image3.png"     style=" width:300px; padding: 10px; " >
<img align="left" src="image4.png"     style=" width:300px; padding: 10px; " >


## Q-Learning Example
- Set gamma = 0.8
- Initialize Q Matrix as zero
- From node 1, agent can either go to node 3 or 5; let's select 5
- From node 5, calculate maximum Q value for this next state based on potential actions
- Q(state, action) = R(state, action) + gamma * max[Q(next state, all actions)]

<img align="left" src="image5.png"     style=" width:800px; padding: 10px; " >

In [2]:
import numpy as np

In [14]:
Q = np.matrix(np.zeros([6,6]))
initial_state = 1
gamma = 0.8
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [15]:
# -1 -> NULL
R = np.matrix([
    [-1, -1, -1, -1,  0, -1],
    [-1, -1, -1,  0, -1, 100],
    [-1, -1, -1,  0, -1, -1],
    [-1,  0,  0, -1,  0, -1],
    [ 0, -1, -1,  0, -1, 100],
    [-1,  0, -1, -1,  0, 100]
])
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [  0,  -1,  -1,   0,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [16]:
print(R[2])
current_state_row = R[2,]
print(np.where(current_state_row >= 0))

[[-1 -1 -1  0 -1 -1]]
(array([0], dtype=int64), array([3], dtype=int64))


In [17]:
def avaliable_actions(state):
    current_state_row = R[state,]
    avail_act = np.where(current_state_row >= 0)[1]
    return avail_act

In [20]:
avaliable_act = avaliable_actions(initial_state)
avaliable_act

array([3, 5], dtype=int64)

In [21]:
def sample_next_action(avaliable_actions_range):
    next_action = int(np.random.choice(avaliable_actions_range))
    return next_action

action = sample_next_action(avaliable_act)
action

5

In [22]:
def update(current_state, action, gamma):
    max_index = np.where(Q[action,] == np.max(Q[action,]))[1]
    
    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index, size=1)[0])
    else:
        max_index = int(max_index.item())
    
    max_value = Q[action, max_index]
    
    Q[current_state, action] = R[current_state, action] + gamma * max_value